export const SECONDARY_COLOR = '#c9c9c9'
export const ACCENT_COLOR = '#fca252'
export const PRIMARY_COLOR = '#27222c'
export const WHITE_COLOR = '#F9F9F9'
export const BACKGROUND_COLOR = '#d5dae5'
export const BACKGROUND_SECONDARY_COLOR = '#edeef1'
export const DANGER_COLOR = '#f16262'