import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Dashboard } from '../components/Dashboard/Dashboard'
import BasicLayout from '../layout/Basic'

const Home: NextPage = () => {
  return (
    <BasicLayout>
      <Head>
        <title>BlogApp</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Dashboard />
      </main>
    </BasicLayout>
  )
}

export default Home
